# SPDX-License-Identifier: GPL-2.0
#
# Makefile for HostCC (Host Congestion Control)
#

obj-$(CONFIG_HOSTCC) += hostcc.o

hostcc-y := hostcc-core.o hostcc-signals.o hostcc-local-response.o hostcc-network-response.o hostcc-logging.o hostcc-sysfs.o
